In [15]:
import numpy as np

In [16]:
my_list = [1, 2, 3]

In [17]:
my_arr = np.array(my_list)
my_arr

array([1, 2, 3])

In [18]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [38]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random data

In [144]:
# Array with random digits
np.random.rand(5, 5)

array([[0.33316665, 0.0082776 , 0.47137388, 0.41047329, 0.93320503],
       [0.94055328, 0.27722365, 0.97967372, 0.44385262, 0.11409671],
       [0.41621986, 0.86445787, 0.24842618, 0.7381029 , 0.62732978],
       [0.08979292, 0.10219338, 0.14278506, 0.81459111, 0.81405211],
       [0.8486095 , 0.175853  , 0.29569755, 0.74613767, 0.06978705]])

In [142]:
# Array with from the "standard normal" distribution
np.random.randn(10)

array([ 1.56935589, -1.64411622, -0.10804174,  0.597932  ,  0.95723404,
       -0.85012454,  0.45231437,  2.06227371,  0.12334794, -1.84299564])

In [273]:
# Random digit
np.random.randint(0, 101)

48

In [281]:
np.random.randint(0, 101, (2, 2))

array([[100,  30],
       [  6,  65]])

In [308]:
# Set random numbers
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [314]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [313]:
# Reshape array
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [326]:
ranarr = np.random.randint(0, 101, 10)

In [327]:
ranarr

array([ 14,  61,  61,  46,  61,  50,  54,  63,   2, 100])

In [328]:
ranarr.max()

100

In [329]:
ranarr.min()

2

In [330]:
# Position of max argument
ranarr.argmax()

9

In [332]:
# Position of min argument
ranarr.argmin()

8

In [335]:
arr.shape

(25,)

In [336]:
arr = arr.reshape(5, 5)

In [337]:
arr.shape

(5, 5)